# Generated by Django 4.0.3 on 2022-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('user', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
